---
name: "🖤Refactoring"
description: "Code Refactoring"
labels:
  - feature
body:
- type: textarea
  id: why
  attributes:
    label: Refactoring Concept?
    description: Describe the concept of refactoring
  validations:
    required: true
- type: textarea
  id: concept
  attributes:
    label: Why
    description: Why this repository should take that code concept
  validations:
    required: true